import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { SideBar } from "./components/SideBar";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "Khulood Maqbool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Anybody:ital,wght@0,100..900;1,100..900&family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet" />
      </head>
      <body>
      <div className=" flex w-full flex-between ">
        {/* <div className=" block  md:flex lg:flex lg:w-full md:w-full w-0 flex-between "> */}
          <div className="md:w-1/5 lg:md:w-1/5">
            <SideBar />
          </div>
          <div className="md:w-4/5 lg:w-4/5">
            <Header />
            <div className="px-5">
              {children}
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
